name: continuous_integration_build
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["core"]
jobs:
  continuous_integration_build:
    runs-on: macos-latest
    steps:
      - name: git_initialization
        run: git config --global init.defaultBranch core
      - name: continuous_integration:repository->checkout
        uses: actions/checkout@v4
        with:
          path: zoe
      - name: checkout_cer0
        uses: actions/checkout@v4
        with:
          repository: alic3dev/cer0
          path: cer0
      - name: checkout_clic3
        uses: actions/checkout@v4
        with:
          repository: alic3dev/clic3
          path: clic3
      - name: checkout_interrupt_handler
        uses: actions/checkout@v4
        with:
          repository: alic3dev/interrupt_handler
          path: interrupt_handler
      - name: checkout_math_c
        uses: actions/checkout@v4
        with:
          repository: alic3dev/math_c
          path: math_c
      - name: checkout_metil
        uses: actions/checkout@v4
        with:
          repository: alic3dev/metil
          path: metil
      - name: checkout_rand
        uses: actions/checkout@v4
        with:
          repository: alic3dev/rand
          path: rand
      - name: make_clic3
        run: cd clic3 && make clic3_dylib
      - name: make_cer0
        run: cd cer0 && make cer0_dylib
      - name: make_interrupt_handler
        run: cd interrupt_handler && make interrupt_handler_dylib
      - name: make_math_c
        run: cd math_c && make math_c_dylib
      - name: make_metil
        run: cd metil && make metil
      - name: make_rand
        run: cd rand && make
      - name: make_zoe
        run: cd zoe && disable_metal_fast_options=1 make
