name: continuous_integration_build
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["*"]
env:
  enabled_caching: 1
  enabled_caching_cer0: 1
  enabled_caching_clic3: 1
  enabled_caching_interrupt_handler: 1
  enabled_caching_math_c: 1
  enabled_caching_metil: 1
  enabled_caching_rand: 1
  key_cache_cer0: cache_cer0_0_0_0
  key_cache_clic3: cache_clic3_0_0_0
  key_cache_interrupt_handler: cache_interrupt_handler_0_0_0
  key_cache_math_c: cache_math_c_0_0_0
  key_cache_metil: cache_metil_0_0_0
  key_cache_rand: cache_rand_0_0_0
  target_device_version_macos: 15.5
  target_standard_metal: metal3.2
jobs:
  continuous_integration_build:
    runs-on: macos-latest
    steps:
      - name: git_initialization
        run: git config --global init.defaultBranch core
      - name: continuous_integration:repository->checkout
        uses: actions/checkout@v4
        with:
          path: zoe
      - name: cache_restore_cer0
        id: cache_restore_cer0
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_cer0 == '1' }}
        uses: actions/cache/restore@v4
        with:
          path: cer0
          key: ${{ env.key_cache_cer0 }}
      - name: cache_restore_clic3
        id: cache_restore_clic3
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_clic3 == '1' }}
        uses: actions/cache/restore@v4
        with:
          path: clic3
          key: ${{ env.key_cache_clic3 }}
      - name: cache_restore_interrupt_handler
        id: cache_restore_interrupt_handler
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_interrupt_handler == '1' }}
        uses: actions/cache/restore@v4
        with:
          path: interrupt_handler
          key: ${{ env.key_cache_interrupt_handler }}
      - name: cache_restore_math_c
        id: cache_restore_math_c
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_math_c == '1' }}
        uses: actions/cache/restore@v4
        with:
          path: math_c
          key: ${{ env.key_cache_math_c }}
      - name: cache_restore_metil
        id: cache_restore_metil
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_metil == '1' }}
        uses: actions/cache/restore@v4
        with:
          path: metil
          key: ${{ env.key_cache_metil }}
      - name: cache_restore_rand
        id: cache_restore_rand
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_rand == '1' }}
        uses: actions/cache/restore@v4
        with:
          path: rand
          key: ${{ env.key_cache_rand }}
      - name: checkout_cer0
        if: steps.cache_restore_cer0.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: alic3dev/cer0
          path: cer0
      - name: checkout_clic3
        if: steps.cache_restore_clic3.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: alic3dev/clic3
          path: clic3
      - name: checkout_interrupt_handler
        if: steps.cache_restore_interrupt_handler.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: alic3dev/interrupt_handler
          path: interrupt_handler
      - name: checkout_math_c
        if: steps.cache_restore_math_c.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: alic3dev/math_c
          path: math_c
      - name: checkout_metil
        if: steps.cache_restore_metil.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: alic3dev/metil
          path: metil
      - name: checkout_rand
        if: steps.cache_restore_rand.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: alic3dev/rand
          path: rand
      - name: make_clic3
        if: steps.cache_restore_clic3.outputs.cache-hit != 'true'
        run: cd clic3 && make clic3_dylib target_device_version=${{ env.target_device_version_macos }}
      - name: make_cer0
        if: steps.cache_restore_cer0.outputs.cache-hit != 'true'
        run: cd cer0 && make cer0_dylib target_device_version=${{ env.target_device_version_macos }}
      - name: make_interrupt_handler
        if: steps.cache_restore_interrupt_handler.outputs.cache-hit != 'true'
        run: cd interrupt_handler && make interrupt_handler_dylib target_device_version=${{ env.target_device_version_macos }}
      - name: make_math_c
        if: steps.cache_restore_math_c.outputs.cache-hit != 'true'
        run: cd math_c && make math_c_dylib target_device_version=${{ env.target_device_version_macos }}
      - name: make_metil
        if: steps.cache_restore_metil.outputs.cache-hit != 'true'
        run: cd metil && make metil target_device_version=${{ env.target_device_version_macos }} target_standard_metal=${{ env.target_standard_metal }}
      - name: make_rand
        if: steps.cache_restore_rand.outputs.cache-hit != 'true'
        run: cd rand && make rand_dylib target_device_version=${{ env.target_device_version_macos }}
      - name: make_zoe
        run: cd zoe && make disable_metal_fast_options=1 target_device_version=${{ env.target_device_version_macos }} target_standard_metal=${{ env.target_standard_metal }}
      - name: cache_save_cer0
        id: cache_save_cer0
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_cer0 == '1' && steps.cache_restore_cer0.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: cer0
          key: ${{ env.key_cache_cer0 }}
      - name: cache_save_clic3
        id: cache_save_clic3
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_clic3 == '1' && steps.cache_restore_clic3.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: clic3
          key: ${{ env.key_cache_clic3 }}
      - name: cache_save_interrupt_handler
        id: cache_save_interrupt_handler
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_interrupt_handler == '1' && steps.cache_restore_interrupt_handler.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: interrupt_handler
          key: ${{ env.key_cache_interrupt_handler }}
      - name: cache_save_math_c
        id: cache_save_math_c
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_math_c == '1' && steps.cache_restore_math_c.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: math_c
          key: ${{ env.key_cache_math_c }}
      - name: cache_save_metil
        id: cache_save_metil
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_metil == '1' && steps.cache_restore_metil.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: metil
          key: ${{ env.key_cache_metil }}
      - name: cache_save_rand
        id: cache_save_rand
        if: ${{ env.enabled_caching == '1' && env.enabled_caching_rand == '1' && steps.cache_restore_rand.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: rand
          key: ${{ env.key_cache_rand }}
